
extensions = {
    'txt': 'TextFiles',
    'pdf': 'PDFFiles',
    'docx': 'WordDocuments',
    'xlsx': 'ExcelFiles',
    'pptx': 'PowerPointFiles',
    'jpg': 'ImageFiles',
    'png': 'ImageFiles',
    'gif': 'ImageFiles',
    'mp3': 'AudioFiles',
    'mp4': 'VideoFiles',
    'mov': 'VideoFiles',
    'zip': 'CompressedFiles',
    'rar': 'CompressedFiles',
    'md': 'MarkdownFiles',
    'py': 'PythonFiles',
    'cpp': 'C++Files',
    'java': 'JavaFiles',
    'js': 'JavaScriptFiles',
    'html': 'HTMLFiles',
    'css': 'CSSFiles',
    'json': 'JSONFiles',
    'xml': 'XMLFiles',
    'yaml': 'YAMLFiles',
    'csv': 'CSVFiles',
    'tsv': 'TSVFiles',
    'sql': 'SQLFiles',
    'php': 'PHPFiles',
    'go': 'GoFiles',
    'bash': 'BashFiles',
    'sh': 'BashFiles',
    'c': 'CFiles'
}